// Hello World Template
// This is a test template to verify the print system works correctly.

#set page(
  width: 8.5in,
  height: 11in,
  margin: 1in,
)

#set text(
  size: 12pt,
)

#align(center)[
  #text(size: 24pt, weight: "bold")[Hello, Mimir!]
]

#v(1em)

This is a test document generated by the Mimir print system using Typst.

#if "name" in data [
  #v(1em)
  *Character Name:* #data.name
]

#if "message" in data [
  #v(1em)
  *Message:* #data.message
]

#v(2em)

#line(length: 100%)

#v(1em)

#align(center)[
  #text(size: 10pt, fill: gray)[
    Generated by mimir-dm-print
  ]
]
