// Mimir Spell List Template
// Table format for spell lists (US Letter)

#import "/_shared/styles.typ": *
#import "/_shared/components.typ": *
#import "/_shared/icons.typ": *

// Document setup
#show: mimir-doc.with(margin: 0.5in)

// Helper to safely get nested data
#let get(obj, key, default: none) = {
  if obj != none and key in obj { obj.at(key) } else { default }
}

// =============================================================================
// DATA EXTRACTION
// =============================================================================

#let list-title = get(data, "title", default: "Spell List")
#let spells = get(data, "spells", default: ())
#let show-description = get(data, "show_description", default: false)

// Level string helper
#let level-str(level) = {
  if level == 0 { "C" }
  else { str(level) }
}

// School abbreviation
#let school-abbrev(school) = {
  let s = lower(school)
  if s == "abjuration" { "Abj" }
  else if s == "conjuration" { "Con" }
  else if s == "divination" { "Div" }
  else if s == "enchantment" { "Enc" }
  else if s == "evocation" { "Evo" }
  else if s == "illusion" { "Ill" }
  else if s == "necromancy" { "Nec" }
  else if s == "transmutation" { "Tra" }
  else { school.slice(0, 3) }
}

// =============================================================================
// HEADER
// =============================================================================

#align(center)[
  #title-text(list-title)
]

#v(spacing.md)

// Group spells by level
#let grouped = (:)
#for spell in spells {
  let level = get(spell, "level", default: 0)
  let key = str(level)
  if key not in grouped {
    grouped.insert(key, ())
  }
  grouped.at(key).push(spell)
}

// =============================================================================
// SPELL TABLE
// =============================================================================

#for level in grouped.keys().sorted() {
  let level-int = int(level)
  let level-spells = grouped.at(level)

  // Level header
  block(
    width: 100%,
    fill: colors.background-alt,
    inset: spacing.sm,
    above: spacing.md,
    below: spacing.sm,
  )[
    #text(weight: "bold")[
      #if level-int == 0 [Cantrips]
      else [#level-int#if level-int == 1 [st] else if level-int == 2 [nd] else if level-int == 3 [rd] else [th] Level]
    ]
    #h(1fr)
    #text(size: sizes.sm, fill: colors.text-secondary)[#level-spells.len() spells]
  ]

  // Sort spells by name
  let sorted-spells = level-spells.sorted(key: s => get(s, "name", default: ""))

  // Spell table
  table(
    columns: if show-description { (auto, auto, auto, auto, auto, 1fr) } else { (1fr, auto, auto, auto, auto) },
    stroke: none,
    inset: (x: spacing.sm, y: spacing.xs),
    fill: (_, y) => if calc.rem(y, 2) == 0 { colors.background-alt } else { white },

    // Header row
    [*Name*],
    [*School*],
    [*Time*],
    [*Range*],
    [*Comp*],
    ..if show-description { ([*Description*],) } else { () },

    // Data rows
    ..for spell in sorted-spells {
      let name = get(spell, "name", default: "?")
      let school = get(spell, "school", default: "?")
      let cast-time = get(spell, "casting_time", default: get(spell, "cast_time", default: "?"))
      let range = get(spell, "range", default: "?")
      let components = get(spell, "components", default: "?")
      let concentration = get(spell, "concentration", default: false)
      let ritual = get(spell, "ritual", default: false)
      let description = get(spell, "description", default: "")

      (
        [
          #text(weight: "medium")[#name]
          #if concentration [#text(size: sizes.xs, fill: colors.text-secondary)[ (C)]]
          #if ritual [#text(size: sizes.xs, fill: colors.text-secondary)[ (R)]]
        ],
        text(size: sizes.sm)[#school-abbrev(school)],
        text(size: sizes.sm)[#cast-time],
        text(size: sizes.sm)[#range],
        text(size: sizes.sm)[#components],
        ..if show-description { (text(size: sizes.xs)[#description.codepoints().slice(0, calc.min(100, description.codepoints().len())).join("")...],) } else { () },
      )
    }
  )
}

// =============================================================================
// LEGEND
// =============================================================================

#v(1fr)

#block(
  width: 100%,
  inset: spacing.sm,
  stroke: (top: 0.5pt + colors.border-light),
)[
  #text(size: sizes.xs, fill: colors.text-secondary)[
    *Legend:*
    (C) = Concentration,
    (R) = Ritual
    |
    *Schools:*
    Abj = Abjuration,
    Con = Conjuration,
    Div = Divination,
    Enc = Enchantment,
    Evo = Evocation,
    Ill = Illusion,
    Nec = Necromancy,
    Tra = Transmutation
  ]
]

#align(center)[
  #small-text[Generated by Mimir]
]
