// Mimir Print System - Combined Campaign Export Template
// Renders all campaign documents as a single PDF with cover and table of contents

#import "/_shared/styles.typ": *

// Expected data structure (injected by PrintService):
// - campaign_name: Name of the campaign (string)
// - documents: Array of document objects, each with:
//   - title: Document title
//   - document_type: Type (e.g., "session_outline")
//   - content: Pre-converted Typst content

#let campaign-name = data.at("campaign_name", default: "Campaign Documents")
#let documents = data.at("documents", default: ())

// Format document type for display
#let format-type(doc-type) = {
  doc-type.replace("_", " ").split(" ").map(word => {
    if word.len() > 0 {
      upper(word.at(0)) + word.slice(1)
    } else {
      word
    }
  }).join(" ")
}

// Group documents by type
#let group-documents(docs) = {
  let groups = (:)
  for doc in docs {
    let doc-type = doc.at("document_type", default: "other")
    if doc-type not in groups {
      groups.insert(doc-type, ())
    }
    groups.at(doc-type).push(doc)
  }
  groups
}

// Base page setup (no header/footer for cover page)
#set page(
  paper: "us-letter",
  margin: (top: 1in, bottom: 0.75in, left: 0.75in, right: 0.75in),
)

// Base text settings
#set text(
  font: font-body,
  size: sizes.base,
  fill: colors.text,
)

// Heading styles
#show heading.where(level: 1): it => {
  v(spacing.lg)
  text(size: sizes.xxl, weight: "bold", font: font-heading, it.body)
  v(spacing.md)
}

#show heading.where(level: 2): it => {
  v(spacing.md)
  text(size: sizes.xl, weight: "bold", font: font-heading, it.body)
  v(spacing.sm)
}

#show heading.where(level: 3): it => {
  v(spacing.sm)
  text(size: sizes.lg, weight: "bold", font: font-heading, it.body)
  v(spacing.xs)
}

// Paragraph settings
#set par(
  leading: 0.65em,
  justify: true,
  first-line-indent: 0pt,
)

// List settings
#set list(
  indent: 1em,
  body-indent: 0.5em,
)

#set enum(
  indent: 1em,
  body-indent: 0.5em,
)

// Blockquote styling
#show quote: it => {
  block(
    width: 100%,
    inset: (left: 1em, y: 0.5em),
    stroke: (left: 2pt + colors.border-light),
    fill: colors.background-alt,
  )[
    #set text(style: "italic")
    #it.body
  ]
}

// =============================================================================
// COVER PAGE
// =============================================================================

#align(center + horizon)[
  #v(2in)

  #text(size: 36pt, weight: "bold", font: font-heading, campaign-name)

  #v(1in)

  #text(size: sizes.xl, fill: colors.text-secondary)[Campaign Documents]

  #v(2in)

  #line(length: 3in, stroke: 1pt + colors.border-light)

  #v(0.5in)

  #text(size: sizes.sm, fill: colors.text-secondary)[Generated by Mimir]
]

#pagebreak()

// =============================================================================
// TABLE OF CONTENTS
// =============================================================================

#let grouped = group-documents(documents)

= Table of Contents

#v(spacing.lg)

#for (doc-type, docs) in grouped [
  == #format-type(doc-type)
  #v(spacing.sm)

  #for doc in docs [
    #let doc-title = doc.at("title", default: "Untitled")
    - #doc-title
  ]

  #v(spacing.md)
]

#pagebreak()

// =============================================================================
// DOCUMENT PAGES
// =============================================================================

#for (i, doc) in documents.enumerate() [
  #let doc-title = doc.at("title", default: "Untitled")
  #let doc-type = doc.at("document_type", default: "document")
  #let content = doc.at("content", default: "")

  // Document type badge
  #set text(size: sizes.sm, fill: colors.text-secondary)
  #format-type(doc-type)

  // Document title
  #v(spacing.sm)
  #align(center)[
    #text(size: sizes.title, weight: "bold", font: font-heading, doc-title)
  ]

  #v(spacing.lg)

  // Document content
  #set text(size: sizes.base, fill: colors.text)
  #eval(content, mode: "markup")

  // Page break between documents (except after last)
  #if i < documents.len() - 1 [
    #pagebreak()
  ]
]

// Footer on last page
#v(1fr)
#align(center)[
  #text(size: sizes.sm, fill: colors.text-secondary)[Generated by Mimir]
]
