// Mimir Print System - Campaign Document Template
// Renders a single campaign document (session outline, NPC profile, location, etc.)

#import "/_shared/styles.typ": *

// Expected data structure (injected by PrintService):
// - title: Document title (string)
// - document_type: Type of document (string, e.g., "session_outline", "npc_profile")
// - campaign_name: Name of the campaign (string, optional)
// - content: Pre-converted Typst content (string)

// Format document type for display (e.g., "session_outline" -> "Session Outline")
#let format-type(doc-type) = {
  doc-type.replace("_", " ").split(" ").map(word => {
    if word.len() > 0 {
      upper(word.at(0)) + word.slice(1)
    } else {
      word
    }
  }).join(" ")
}

#let title = data.at("title", default: "Untitled Document")
#let doc-type = data.at("document_type", default: "document")
#let campaign = data.at("campaign_name", default: none)
#let content = data.at("content", default: "")

// Page setup with headers and footers
#set page(
  paper: "us-letter",
  margin: (top: 1in, bottom: 0.75in, left: 0.75in, right: 0.75in),
  header: {
    set text(size: sizes.sm, fill: colors.text-secondary)
    grid(
      columns: (1fr, 1fr),
      align: (left, right),
      [#format-type(doc-type)],
      if campaign != none { campaign } else { [] }
    )
    v(4pt)
    line(length: 100%, stroke: 0.5pt + colors.border-light)
  },
  footer: {
    line(length: 100%, stroke: 0.5pt + colors.border-light)
    v(4pt)
    set text(size: sizes.xs, fill: colors.text-secondary)
    grid(
      columns: (1fr, 1fr),
      align: (left, right),
      [Generated by Mimir],
      [#context counter(page).display("1")]
    )
  }
)

// Base text settings
#set text(
  font: font-body,
  size: sizes.base,
  fill: colors.text,
)

// Heading styles
#show heading.where(level: 1): it => {
  v(spacing.lg)
  text(size: sizes.xxl, weight: "bold", font: font-heading, it.body)
  v(spacing.md)
}

#show heading.where(level: 2): it => {
  v(spacing.md)
  text(size: sizes.xl, weight: "bold", font: font-heading, it.body)
  v(spacing.sm)
}

#show heading.where(level: 3): it => {
  v(spacing.sm)
  text(size: sizes.lg, weight: "bold", font: font-heading, it.body)
  v(spacing.xs)
}

// Paragraph settings
#set par(
  leading: 0.65em,
  justify: true,
  first-line-indent: 0pt,
)

// List settings
#set list(
  indent: 1em,
  body-indent: 0.5em,
)

#set enum(
  indent: 1em,
  body-indent: 0.5em,
)

// Blockquote styling
#show quote: it => {
  block(
    width: 100%,
    inset: (left: 1em, y: 0.5em),
    stroke: (left: 2pt + colors.border-light),
    fill: colors.background-alt,
  )[
    #set text(style: "italic")
    #it.body
  ]
}

// Document title
#align(center)[
  #text(size: sizes.title, weight: "bold", font: font-heading, title)
]

#v(spacing.lg)

// Document content (pre-converted to Typst)
#eval(content, mode: "markup")
